### ISSUE TITLE
Double specification of material_properties in movingCylinder

### ISSUE THREAD

**Issue by gantech** [NaluCFD/NaluRtest#5]
Lines 155 - 168

```
    material_properties:

      target_name: block_10

    material_properties:
      target_name: block_10
      specifications:
        - name: density
          type: constant
          value: 1.0

        - name: viscosity
          type: constant
          value: 0.0075
```

 Is this done on purpose to catch an error? Should yaml-cpp always read the last one?
