### ISSUE TITLE
Double specification of wall_user_data in movingCylinder

### ISSUE THREAD

**Issue by gantech** [NaluCFD/NaluRtest#9]
Lines 92-93

```
    - wall_boundary_condition: bc_cyliner
      target_name: surface_5
      wall_user_data:
      wall_user_data:
        user_function_name:
         mesh_displacement: sinusoidal
        user_function_parameters:
         mesh_displacement: [0.20]
```
